import type { Course, DashboardData, ReviewQuestion, Team, VocabularyItem } from '@/lib/types';

// Local presentation data. It is reachable only when NEXT_PUBLIC_LEARN_DEMO_MODE=true.
// Real catalog, permissions, progress and vocabulary always come from api.pokyh.com.
export const demoCourses: Course[] = [
  {
    id: 'italian-foundations',
    slug: 'italiano-fondamenti',
    title: 'Italiano: Fondamenti',
    description: 'Alltagssprache, Artikel und sichere erste Gespräche.',
    language: 'Italienisch',
    sourceLanguage: 'Deutsch',
    level: 'A1',
    accent: 'coral',
    category: 'Sprachen',
    visibility: 'public',
    state: 'active',
    modules: 6,
    lessons: 28,
    vocabularyCount: 196,
    progress: 62,
    nextLesson: 'Artikel: il, lo, la',
    ownerName: 'Pокyh Learn',
    isEnrolled: true,
    updatedAt: 'Heute',
  },
  {
    id: 'english-tenses',
    slug: 'english-tenses',
    title: 'English Tenses',
    description: 'Zeitformen verstehen, anwenden und in echten Sätzen festigen.',
    language: 'Englisch',
    sourceLanguage: 'Deutsch',
    level: 'B1',
    accent: 'lavender',
    category: 'Sprachen',
    visibility: 'public',
    state: 'active',
    modules: 8,
    lessons: 36,
    vocabularyCount: 248,
    progress: 34,
    nextLesson: 'Present perfect oder past simple?',
    ownerName: 'Pокyh Learn',
    isEnrolled: true,
    updatedAt: 'Gestern',
  },
  {
    id: 'travel-italian',
    slug: 'italiano-in-viaggio',
    title: 'Italiano in viaggio',
    description: 'Praktische Sätze für Café, Hotel, Bahnhof und unterwegs.',
    language: 'Italienisch',
    sourceLanguage: 'Deutsch',
    level: 'A1',
    accent: 'sun',
    category: 'Reisen',
    visibility: 'team',
    state: 'active',
    modules: 5,
    lessons: 22,
    vocabularyCount: 138,
    ownerName: 'Italienisch Gruppe',
    enrolledCount: 14,
    updatedAt: 'Vor 2 Tagen',
  },
  {
    id: 'business-writing',
    slug: 'business-english-writing',
    title: 'Business English: Writing',
    description: 'Klare E-Mails, präzise Formulierungen und professioneller Ton.',
    language: 'Englisch',
    sourceLanguage: 'Deutsch',
    level: 'B2',
    accent: 'mint',
    category: 'Beruf',
    visibility: 'public',
    state: 'active',
    modules: 7,
    lessons: 31,
    vocabularyCount: 174,
    ownerName: 'Pокyh Learn',
    updatedAt: 'Diese Woche',
  },
];

export const demoDashboard: DashboardData = {
  displayName: 'Felix',
  dailyGoalMinutes: 20,
  analytics: {
    range: '7d',
    timezone: 'Europe/Rome',
    dataAvailableSince: '2026-09-01',
    totals: { attempts: 28, answers: 86, correctAnswers: 72, accuracyPercent: 83.7, activeDays: 7, streakDays: 7 },
    days: [
      { dayKey: '2026-09-06', attempts: 3, answers: 12, correctAnswers: 10 },
      { dayKey: '2026-09-07', attempts: 4, answers: 14, correctAnswers: 12 },
      { dayKey: '2026-09-08', attempts: 4, answers: 10, correctAnswers: 8 },
      { dayKey: '2026-09-09', attempts: 5, answers: 17, correctAnswers: 14 },
      { dayKey: '2026-09-10', attempts: 4, answers: 11, correctAnswers: 9 },
      { dayKey: '2026-09-11', attempts: 4, answers: 13, correctAnswers: 11 },
      { dayKey: '2026-09-12', attempts: 4, answers: 9, correctAnswers: 8 },
    ],
    queues: { due: 14, wrong: 6, fresh: 8, nextDueAt: '2026-09-13T08:00:00.000Z' },
    recommendation: { kind: 'due', count: 14, href: '/practice?queue=due' },
    courses: [],
  },
  activeCourses: demoCourses.filter((course) => course.isEnrolled),
  reviewCards: [
    {
      id: 'review-1',
      prompt: 'la stazione',
      context: 'Welche deutsche Bedeutung gehört dazu?',
      kind: 'due',
      courseTitle: 'Italiano: Fondamenti',
    },
    {
      id: 'review-2',
      prompt: 'I have been waiting',
      context: 'Welche Zeitform passt hier?',
      kind: 'mistake',
      courseTitle: 'English Tenses',
    },
    {
      id: 'review-3',
      prompt: 'il biglietto',
      context: 'Welcher Artikel gehört zum Wort?',
      kind: 'new',
      courseTitle: 'Italiano in viaggio',
    },
  ],
};

export const demoVocabulary: VocabularyItem[] = [
  {
    id: 'voc-1',
    courseId: 'italian-foundations',
    source: 'stazione',
    sourceLanguage: 'it',
    targetLanguage: 'de',
    article: 'la',
    partOfSpeech: 'Nomen',
    contextSentence: 'La stazione è vicina.',
    state: 'due',
    validation: 'verified',
    readyForQuiz: true,
  },
  {
    id: 'voc-2',
    courseId: 'italian-foundations',
    source: 'biglietto',
    sourceLanguage: 'it',
    targetLanguage: 'de',
    article: 'il',
    partOfSpeech: 'Nomen',
    contextSentence: 'Ho un biglietto per Roma.',
    state: 'mistake',
    validation: 'verified',
    readyForQuiz: true,
  },
  {
    id: 'voc-3',
    courseId: 'travel-italian',
    source: 'prenotare',
    sourceLanguage: 'it',
    targetLanguage: 'de',
    partOfSpeech: 'Verb',
    contextSentence: 'Vorrei prenotare un tavolo.',
    state: 'learning',
    validation: 'manual',
    readyForQuiz: true,
  },
  {
    id: 'voc-4',
    courseId: 'english-tenses',
    source: 'delay',
    sourceLanguage: 'en',
    targetLanguage: 'de',
    partOfSpeech: 'Nomen',
    contextSentence: 'The train has a delay.',
    state: 'mastered',
    validation: 'verified',
    readyForQuiz: true,
  },
];

export const demoQuestions: ReviewQuestion[] = [
  {
    id: 'question-1',
    courseId: 'italian-foundations',
    prompt: 'Wie sagt man „der Bahnhof“ auf Italienisch?',
    direction: 'SOURCE_TO_TARGET',
    sourceLanguage: 'de',
    targetLanguage: 'it',
    hint: 'Denk an den femininen Artikel.',
    demoAnswer: 'la stazione',
    demoAcceptedAnswers: ['la stazione', 'stazione'],
    demoExplanation: 'Stazione ist im Italienischen feminin: la stazione.',
    article: 'la',
    example: 'La stazione è vicino al centro.',
    courseTitle: 'Italiano: Fondamenti',
    kind: 'mistake',
  },
  {
    id: 'question-2',
    courseId: 'english-tenses',
    prompt: 'Ergänze: “I ___ here since Monday.”',
    direction: 'SOURCE_TO_TARGET',
    sourceLanguage: 'de',
    targetLanguage: 'en',
    hint: 'Die Handlung begann in der Vergangenheit und dauert an.',
    demoAnswer: 'have been',
    demoAcceptedAnswers: ['have been'],
    demoExplanation: 'Für einen andauernden Zustand mit “since” nutzt man present perfect.',
    example: 'I have been here since Monday.',
    courseTitle: 'English Tenses',
    kind: 'due',
  },
];

export const demoTeams: Team[] = [
  {
    id: 'team-italian',
    slug: 'italienisch-gruppe',
    name: 'Italienisch Gruppe',
    description: 'Gemeinsam Wörter, Übungen und Reise-Szenarien üben.',
    memberCount: 14,
    role: 'admin',
    courseCount: 3,
    accent: 'coral',
  },
  {
    id: 'team-english',
    slug: 'english-study-circle',
    name: 'English Study Circle',
    description: 'Tenses, writing und Vokabeln für den Alltag.',
    memberCount: 8,
    role: 'member',
    courseCount: 2,
    accent: 'lavender',
  },
];
